[project]
name = "adeval"
version = "0.1.0"
# Hydra bug in 3.14, Ray in beta for 3.13
requires-python = ">=3.10, <3.13.0"
dependencies = ["rich", "py123d[av2, nuplan]", "nuplan-devkit"]

[project.optional-dependencies]
dev = ["build", "pytest", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
